### ISSUE TITLE
sam validate breaks when using Auth block under AWS::Serverless::Api

### ISSUE THREAD

**Issue by terlar** [awslabs/aws-sam-cli#1074]
### Description

When having a `template.yaml` including an `Auth` property under `AWS::Serverless::Api` it is invalid with a very confusing error message. If I remove this configuration the `sam validate` command validates properly.

### Steps to reproduce

A `template.yaml` including:
```
  ...
  BaseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyAuthorizer
        Authorizers:
          MyAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: Bearer .*
              ReauthorizeEvery: 299 # Seconds

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: myAuthorizer.handler
  ...
```

### Observed result

I skipped the `--debug` flag as it might include some sensitive information and I didn't see any valuable output there.

With `Auth` config:
```
$ sam validate
Template provided at '/var/opt/template.yaml' was invalid SAM Template.
Error:  
```

Without `Auth` config:
```
$ sam validate
/var/opt/template.yaml is a valid SAM Template
```

### Expected result

The template would be valid even with an Auth section defined.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 0.13.0

**Comment by jfuss** [comment]
@terlar This is an error with your template. I get `[InvalidResourceException('BaseApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")] ('BaseApi', "Auth works only with inline Swagger specified in 'DefinitionBody' property")` when I run validate with the above template.

Side note: You should install in Python3.6+ so you can see the errors with validate instead of the `Error: ` with no additional details.

Closing as the definition is not correct and validate is working as expected.

**Comment by terlar** [comment]
Interesting, because I have successfully deployed this template and are using the `Auth` block. Thank you for the feedback regarding Python 3.6+ I wasn't aware. I will investigate further.

**Comment by terlar** [comment]
I now see errors with python 3, and it makes sense. Is it planned to have support for `Auth` without using inline Swagger? And perhaps the most interesting is it unintentional that it actually works when you do it this way?

**Comment by terlar** [comment]
Seems like this has been discovered before:
- https://github.com/awslabs/serverless-application-model/pull/546#issuecomment-442262487

It is supported by SAM and thus works with the sam package/deploy, but not the `sam validate`. I still believe it should be fixed in the validator.

**Comment by terlar** [comment]
However there is already a ticket for it: https://github.com/awslabs/aws-sam-cli/issues/803

**Comment by jfuss** [comment]
Ahh. It's that...

Yes this should be fixed in our validate command. Would you be up for submitting a patch for it? I think our check [here](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/validate/lib/sam_template_validator.py#L93) needs a small adjustment, plus updating/new tests.

**Comment by terlar** [comment]
Thanks for providing the hints where to look, I might be able to do it. If I don't manage to do it today, it will take at least another week until I can take a look at it. But I will give it a shot.

**Comment by jackmcguire1** [comment]
Any progress on this?

**Comment by piersf** [comment]
Was there a solution to this? I got the same error today:

```Error: [InvalidResourceException(ManagementApi', "Invalid value for 'Auth' property")] ('ManagementApi', "Invalid value for 'Auth' property")```

I am using `SAM CLI, version 0.41.0` and `Python 3.7.4`

`sam deploy` works fine, however

Adding  `swagger: 2.0` under `DefinitionBody` as mentioned in https://github.com/awslabs/aws-sam-cli/issues/803#issuecomment-616817020 does not fix anything.
